package com.lody.virtual.client.stub

import android.app.Activity
import android.app.Dialog
import android.content.Intent
import android.os.Bundle
import android.text.Html
import android.view.View
import android.view.Window
import android.widget.Button
import android.widget.ImageView
import android.widget.TextView
import androidx.core.view.isGone
import com.lody.virtual.R
import com.lody.virtual.client.core.VirtualCore
import com.virtualxposed.hook.server.IVHookService
import org.matrix.vector.ipc.HookScope
import org.matrix.vector.ipc.HookScope.Companion.reindexScopes
import org.matrix.vector.service.VectorManagerService
import java.lang.ref.WeakReference
import kotlin.uuid.Uuid

class GrantHookScopesActivity : Activity() {
    companion object {
        private val callbacks = mutableMapOf<String, WeakReference<(Int?) -> Unit>>()

        private fun invokeCallbackOnce(action: Int?, ticket: String?) {
            if (ticket == null) return
            synchronized(callbacks) {
                callbacks[ticket]?.get()?.invoke(action)
                callbacks.remove(ticket)
            }
        }

        fun createStartIntent(
            target: String,
            modulePackageName: String,
            appPackageName: String,
            callback: (Int?) -> Unit
        ): Intent {
            val uuid = Uuid.random().toString()
            synchronized(callbacks) {
                callbacks[uuid] = WeakReference(callback)
            }

            return Intent(VirtualCore.get().context, GrantHookScopesActivity::class.java).apply {
                putExtra(EXTRA_HOOK_TARGET, target)
                putExtra(EXTRA_HOOK_MODULE_CALLER, modulePackageName)
                putExtra(EXTRA_HOOK_APP, appPackageName)
                putExtra(EXTRA_RESULT_TICKET, uuid)
            }
        }

        const val EXTRA_HOOK_TARGET = "com.lody.virtual.client.stub.extra.REQUEST_HOOK_TARGET"
        const val EXTRA_HOOK_MODULE_CALLER =
            "com.lody.virtual.client.stub.extra.EXTRA_HOOK_MODULE_CALLER"
        const val EXTRA_HOOK_APP = "com.lody.virtual.client.stub.extra.EXTRA_HOOK_APP"
        const val EXTRA_HOOK_RESULT = "com.lody.virtual.client.stub.extra.REQUEST_HOOK_RESULT"
        const val EXTRA_RESULT_TICKET = "com.lody.virtual.client.stub.extra.EXTRA_RESULT_TICKET"
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val target = intent.getStringExtra(EXTRA_HOOK_TARGET)
        val caller = intent.getStringExtra(EXTRA_HOOK_MODULE_CALLER)
        val app = intent.getStringExtra(EXTRA_HOOK_APP)
        val ticket = intent.getStringExtra(EXTRA_RESULT_TICKET)

        if (target == null || caller == null || app == null) {
            setResultAndFinish(RESULT_OK, ticket)
            return
        }

        val dialog = createRequestDialog(target, caller, app, ticket)
        dialog.show()
    }

    private fun createRequestDialog(
        target: String,
        caller: String,
        app: String,
        ticket: String?
    ): Dialog {
        val dialog = Dialog(this)
        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE)
        dialog.setContentView(R.layout.permission_request_dialog)
        dialog.window?.setBackgroundDrawableResource(R.drawable.dialog_background)

        val icon = dialog.findViewById<View?>(R.id.dialog_permission_icon) as ImageView
        val messageView = dialog.findViewById<View?>(R.id.dialog_message) as TextView
        val allowButton = dialog.findViewById<View?>(R.id.dialog_button_allow) as Button
        val allowAndRestartButton =
            dialog.findViewById<View?>(R.id.dialog_button_only_once) as Button
        val doNotAllowButton = dialog.findViewById<View?>(R.id.dialog_button_do_not_allow) as Button

        val packageManager = VirtualCore.get().packageManager
        val moduleInfo = packageManager.getPackageInfo(caller, 0)
        val moduleName =
            moduleInfo.applicationInfo?.let { packageManager.getApplicationLabel(it) } ?: caller
        val message = getString(
            R.string.permission_request_hook_message,
            Html.escapeHtml(moduleName), Html.escapeHtml(target)
        )

        messageView.text = Html.fromHtml(message)
        allowButton.text = getString(R.string.permission_manage_allow)
        allowAndRestartButton.text = getString(R.string.permission_manage_allow_and_restart)

        // This feels too clunky as a user when multiple hooks are created
        allowAndRestartButton.isGone = true
        doNotAllowButton.text = getString(R.string.permission_manage_do_not_allow)

        fun getHookScope(action: Int): HookScope {
            return HookScope(
                action,
                target,
                "Scope generated by permission dialog",
                true,
                0,
            )
        }

        allowButton.setOnClickListener {
            val binder = VectorManagerService.getManagerServer() ?: return@setOnClickListener
            val scopes = binder.getHookScopes(caller)

            scopes.add(getHookScope(HookScope.ACTION_ALLOW))
            binder.setHookScopes(caller, scopes.reindexScopes())

            dialog.dismiss()
            setResultAndFinish(RESULT_OK, ticket, IVHookService.ALLOWED)
        }

        allowAndRestartButton.setOnClickListener {
            val binder = VectorManagerService.getManagerServer() ?: return@setOnClickListener
            val scopes = binder.getHookScopes(caller)

            scopes.add(getHookScope(HookScope.ACTION_ALLOW))
            binder.setHookScopes(caller, scopes.reindexScopes())

            // TODO use userId
            VirtualCore.get().killApp(app, 0)
            val intent = VirtualCore.get().getLaunchIntent(app, 0)
            startActivity(intent)

            dialog.dismiss()
            setResultAndFinish(RESULT_OK, ticket, IVHookService.ALLOWED)
        }

        doNotAllowButton.setOnClickListener {
            val binder = VectorManagerService.getManagerServer() ?: return@setOnClickListener
            val scopes = binder.getHookScopes(caller)

            scopes.add(getHookScope(HookScope.ACTION_BLOCK))
            binder.setHookScopes(caller, scopes.reindexScopes())

            dialog.dismiss()
            setResultAndFinish(RESULT_OK, ticket, IVHookService.DENIED)
        }

        dialog.setOnCancelListener {
            setResultAndFinish(
                RESULT_CANCELED,
                ticket
            )
        }

        return dialog
    }

    private fun setResultAndFinish(resultCode: Int, ticket: String?, grantResults: Int? = null) {
        val result = Intent()
        result.putExtra(EXTRA_HOOK_RESULT, grantResults)
        invokeCallbackOnce(grantResults, ticket)
        setResult(resultCode, result)
        finish()
    }
}
