apply plugin: 'com.android.library'

android {
    namespace 'epic.me.weishu.library'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
//    implementation project(path: ':libepic')
    implementation project(path: ':log-client')
    implementation project(path: ':lsplantbridge')
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.getkeepsafe.relinker:relinker:1.4.4' // for load library
    implementation 'com.jakewharton.timber:timber:5.0.1'
}

tasks.withType(JavaCompile) {
    options.deprecation = true
}

group = 'me.weishu.exposed'
version = '0.8.0'
